spring.application.name=tvmaze
server.port=8080
server.servlet.context-path=/v1

url.info=${INFOURL:https://api.tvmaze.com/shows/}
url.search=${SEARCHURL:http://api.tvmaze.com/search/shows?q=}

springdoc.api-docs.enabled=${SWAGGER_ENEABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_ENEABLED:true}

spring.config.import=./application_db.properties,./application_log.properties